import enum

from construct import Enum, Byte, Bytes, PaddedString, Int8sb, Mapping

__all__ = (
    'ANIM',
    'ANIMRABBIT',
    'AREA',
    'BIN_CHAR',
    'BIN_CHAT',
    'BIN_CUSTOM',
    'BIN_DISCONNECTMESSAGE',
    'BIN_GAMEEVENT',
    'BIN_GAMEMODE',
    'BIN_PLUSTIMESTAMP',
    'BIN_SPECTATETARGET',
    'BIN_TEAM',
    'BIN_VERSIONSTRING',
    'CHARACTER',
    'CHAT',
    'DISCONNECT_MESSAGES',
    'GAME',
    'GAMEEVENT',
    'GEM',
    'LATEST_PLUS_VERSION',
    'LIGHT',
    'OBJECT',
    'PLUSTIMESTAMP',
    'SHIELD',
    'SOUND',
    'SPECTATETARGET',
    'SPRITEMODE',
    'STATE',
    'TEAM',
    'TEXTURE',
    'TEXTURE_URL',
    'TIMER',
    'VERSIONSTRING',
    'WEAPON'
)


class GAME:
    class CONNECTION(enum.IntEnum):
        LOCAL = enum.auto()
        ONLINE = enum.auto()
        LAN = enum.auto()

    class CUSTOM(enum.IntEnum):
        NOCUSTOM = enum.auto()
        RT = enum.auto()
        LRS = enum.auto()
        XLRS = enum.auto()
        PEST = enum.auto()
        TB = enum.auto()
        JB = enum.auto()
        DCTF = enum.auto()
        FR = enum.auto()
        TLRS = enum.auto()
        DOM = enum.auto()
        HEAD = enum.auto()

    class MODE(enum.IntEnum):
        SP = enum.auto()
        COOP = enum.auto()
        BATTLE = enum.auto()
        RACE = enum.auto()
        TREASURE = enum.auto()
        CTF = enum.auto()

    class STATE(enum.IntEnum):
        STOPPED = enum.auto()
        STARTED = enum.auto()
        PAUSED = enum.auto()
        PREGAME = enum.auto()
        OVERTIME = enum.auto()


class CHARACTER(enum.IntEnum):
    JAZZ = 0
    SPAZ = enum.auto()
    BIRD = enum.auto()
    LORI = FROG = enum.auto()
    BIRD2 = enum.auto()


class TEAM(enum.IntEnum):
    BLUE = 0
    RED = enum.auto()
    GREEN = enum.auto()
    YELLOW = enum.auto()


class WEAPON(enum.IntEnum):
    BLASTER = enum.auto()
    BOUNCER = enum.auto()
    ICE = enum.auto()
    SEEKER = enum.auto()
    RF = enum.auto()
    TOASTER = enum.auto()
    TNT = enum.auto()
    GUN8 = enum.auto()
    GUN9 = enum.auto()
    CURRENT = enum.auto()


class GEM(enum.IntEnum):
    RED = enum.auto()
    GREEN = enum.auto()
    BLUE = enum.auto()
    PURPLE = enum.auto()


class LIGHT(enum.IntEnum):
    NONE = enum.auto()
    NORMAL = enum.auto()
    POINT = enum.auto()
    POINT2 = enum.auto()
    FLICKER = enum.auto()
    BRIGHT = enum.auto()
    LASERBEAM = enum.auto()
    LASER = enum.auto()
    RING = enum.auto()
    RING2 = enum.auto()
    PLAYER = enum.auto()


class SHIELD(enum.IntEnum):
    NONE = enum.auto()
    FIRE = enum.auto()
    BUBBLE = WATER = enum.auto()
    LIGHTNING = PLASMA = enum.auto()
    LASER = enum.auto()


class SPECTATETARGET(enum.IntEnum):
    BOTTOM_FEEDER = -6
    RING_HOLDER = -5
    BLUE_FLAG = -4
    RED_FLAG = -3
    STOP_SPECTATING_1 = -2
    START_SPECTATING_1 = -1
    START_SPECTATING_2 = 0
    STOP_SPECTATING_2 = 33
    START_SPECTATING_3 = 34


class CHAT(enum.IntEnum):
    NORMAL = enum.auto()
    TEAM_CHAT = enum.auto()
    WHISPER = enum.auto()
    ME = enum.auto()


class TIMER(enum.IntEnum):
    STOPPED = enum.auto()
    STARTED = enum.auto()
    PAUSED = enum.auto()


class STATE(enum.IntEnum):
    START = enum.auto()
    SLEEP = enum.auto()
    WAKE = enum.auto()
    KILL = enum.auto()
    DEACTIVATE = enum.auto()
    WALK = enum.auto()
    JUMP = enum.auto()
    FIRE = enum.auto()
    FLY = enum.auto()
    BOUNCE = enum.auto()
    EXPLODE = enum.auto()
    ROCKETFLY = enum.auto()
    STILL = enum.auto()
    FLOAT = enum.auto()
    HIT = enum.auto()
    SPRING = enum.auto()
    ACTION = enum.auto()
    DONE = enum.auto()
    PUSH = enum.auto()
    FALL = enum.auto()
    FLOATFALL = enum.auto()
    CIRCLE = enum.auto()
    ATTACK = enum.auto()
    FREEZE = enum.auto()
    FADEIN = enum.auto()
    FADEOUT = enum.auto()
    HIDE = enum.auto()
    TURN = enum.auto()
    IDLE = enum.auto()
    EXTRA = enum.auto()
    STOP = enum.auto()
    WAIT = enum.auto()
    LAND = enum.auto()
    DELAYEDSTART = enum.auto()
    ROTATE = enum.auto()
    DUCK = enum.auto()


class AREA(enum.IntEnum):
    ONEWAY = enum.auto()
    HURT = enum.auto()
    VINE = enum.auto()
    HOOK = enum.auto()
    SLIDE = enum.auto()
    HPOLE = enum.auto()
    VPOLE = enum.auto()
    FLYOFF = enum.auto()
    RICOCHET = enum.auto()
    BELTRIGHT = enum.auto()
    BELTLEFT = enum.auto()
    ACCBELTRIGHT = enum.auto()
    ACCBELTLEFT = enum.auto()
    STOPENEMY = enum.auto()
    WINDLEFT = enum.auto()
    WINDRIGHT = enum.auto()
    EOL = enum.auto()
    WARPEOL = enum.auto()
    REVERTMORPH = enum.auto()
    FLOATUP = enum.auto()
    TRIGGERROCK = enum.auto()
    DIMLIGHT = enum.auto()
    SETLIGHT = enum.auto()
    LIMITXSCROLL = enum.auto()
    RESETLIGHT = enum.auto()
    WARPSECRET = enum.auto()
    ECHO = enum.auto()
    ACTIVATEBOSS = enum.auto()
    JAZZLEVELSTART = JAZZSTART = enum.auto()
    SPAZLEVELSTART = SPAZSTART = enum.auto()
    MPLEVELSTART = MPSTART = enum.auto()
    LORILEVELSTART = LORISTART = enum.auto()
    WARP = enum.auto()
    WARPTARGET = enum.auto()
    PATH = AREAID = enum.auto()
    NOFIREZONE = enum.auto()
    TRIGGERZONE = enum.auto()
    SUCKERTUBE = enum.auto()
    TEXT = enum.auto()
    WATERLEVEL = enum.auto()
    MORPHFROG = enum.auto()
    WATERBLOCK = enum.auto()


class OBJECT(enum.IntEnum):
    BLASTERBULLET = enum.auto()
    BOUNCERBULLET = enum.auto()
    ICEBULLET = enum.auto()
    SEEKERBULLET = enum.auto()
    RFBULLET = enum.auto()
    TOASTERBULLET = enum.auto()
    FIREBALLBULLET = enum.auto()
    ELECTROBULLET = enum.auto()
    BLASTERBULLETPU = enum.auto()
    BOUNCERBULLETPU = enum.auto()
    ICEBULLETPU = enum.auto()
    SEEKERBULLETPU = enum.auto()
    RFBULLETPU = enum.auto()
    TOASTERBULLETPU = enum.auto()
    FIREBALLBULLETPU = enum.auto()
    ELECTROBULLETPU = enum.auto()
    FIRESHIELDBULLET = enum.auto()
    WATERSHIELDBULLET = BUBBLESHIELDBULLET = enum.auto()
    LIGHTNINGSHIELDBULLET = PLASMASHIELDBULLET = enum.auto()
    BULLET = enum.auto()
    SMOKERING = enum.auto()
    SHARD = enum.auto()
    EXPLOSION = enum.auto()
    BOUNCEONCE = enum.auto()
    FLICKERGEM = enum.auto()
    LASER = enum.auto()
    UTERUSSPIKEBALL = enum.auto()
    BIRD = enum.auto()
    BUBBLE = enum.auto()
    ICEAMMO3 = enum.auto()
    BOUNCERAMMO3 = enum.auto()
    SEEKERAMMO3 = enum.auto()
    RFAMMO3 = enum.auto()
    TOASTERAMMO3 = enum.auto()
    TNTAMMO3 = enum.auto()
    GUN8AMMO3 = enum.auto()
    GUN9AMMO3 = enum.auto()
    TURTLESHELL = enum.auto()
    SWINGINGVINE = enum.auto()
    BOMB = enum.auto()
    SILVERCOIN = enum.auto()
    GOLDCOIN = enum.auto()
    GUNCRATE = enum.auto()
    CARROTCRATE = enum.auto()
    ONEUPCRATE = enum.auto()
    GEMBARREL = enum.auto()
    CARROTBARREL = enum.auto()
    ONEUPBARREL = enum.auto()
    BOMBCRATE = enum.auto()
    ICEAMMO15 = enum.auto()
    BOUNCERAMMO15 = enum.auto()
    SEEKERAMMO15 = enum.auto()
    RFAMMO15 = enum.auto()
    TOASTERAMMO15 = enum.auto()
    TNT = enum.auto()
    AIRBOARDGENERATOR = enum.auto()
    FROZENSPRING = enum.auto()
    FASTFIRE = enum.auto()
    SPRINGCRATE = enum.auto()
    REDGEM = enum.auto()
    GREENGEM = enum.auto()
    BLUEGEM = enum.auto()
    PURPLEGEM = enum.auto()
    SUPERGEM = enum.auto()
    BIRDCAGE = enum.auto()
    GUNBARREL = enum.auto()
    GEMCRATE = enum.auto()
    MORPH = enum.auto()
    CARROT = enum.auto()
    FULLENERGY = enum.auto()
    FIRESHIELD = enum.auto()
    WATERSHIELD = BUBBLESHIELD = enum.auto()
    LIGHTNINGSHIELD = PLASMASHIELD = enum.auto()
    FASTFEET = enum.auto()
    ONEUP = EXTRALIFE = EXTRALIVE = enum.auto()
    EOLPOST = enum.auto()
    SAVEPOST = CHECKPOINT = enum.auto()
    BONUSPOST = enum.auto()
    REDSPRING = enum.auto()
    GREENSPRING = enum.auto()
    BLUESPRING = enum.auto()
    INVINCIBILITY = enum.auto()
    EXTRATIME = enum.auto()
    FREEZER = FREEZEENEMIES = enum.auto()
    HORREDSPRING = enum.auto()
    HORGREENSPRING = enum.auto()
    HORBLUESPRING = enum.auto()
    BIRDMORPH = enum.auto()
    TRIGGERCRATE = enum.auto()
    FLYCARROT = enum.auto()
    RECTREDGEM = enum.auto()
    RECTGREENGEM = enum.auto()
    RECTBLUEGEM = enum.auto()
    TUFTURT = enum.auto()
    TUFBOSS = enum.auto()
    LABRAT = enum.auto()
    DRAGON = enum.auto()
    LIZARD = enum.auto()
    BEE = BUMBEE = enum.auto()
    RAPIER = enum.auto()
    SPARK = enum.auto()
    BAT = enum.auto()
    SUCKER = enum.auto()
    CATERPILLAR = enum.auto()
    CHESHIRE1 = enum.auto()
    CHESHIRE2 = enum.auto()
    HATTER = enum.auto()
    BILSY = enum.auto()
    SKELETON = enum.auto()
    DOGGYDOGG = enum.auto()
    NORMTURTLE = enum.auto()
    HELMUT = enum.auto()
    DEMON = enum.auto()
    DRAGONFLY = enum.auto()
    MONKEY = enum.auto()
    FATCHICK = enum.auto()
    FENCER = enum.auto()
    FISH = enum.auto()
    MOTH = enum.auto()
    STEAM = enum.auto()
    ROTATINGROCK = enum.auto()
    BLASTERPOWERUP = enum.auto()
    BOUNCERPOWERUP = enum.auto()
    ICEPOWERUP = enum.auto()
    SEEKERPOWERUP = enum.auto()
    RFPOWERUP = enum.auto()
    TOASTERPOWERUP = enum.auto()
    LEFTPADDLE = enum.auto()
    RIGHTPADDLE = enum.auto()
    FIVEHUNDREDBUMP = enum.auto()
    CARROTBUMP = enum.auto()
    APPLE = enum.auto()
    BANANA = enum.auto()
    CHERRY = enum.auto()
    ORANGE = enum.auto()
    PEAR = enum.auto()
    PRETZEL = enum.auto()
    STRAWBERRY = enum.auto()
    STEADYLIGHT = enum.auto()
    PULZELIGHT = PULSELIGHT = enum.auto()
    FLICKERLIGHT = enum.auto()
    QUEEN = enum.auto()
    FLOATSUCKER = enum.auto()
    BRIDGE = enum.auto()
    LEMON = enum.auto()
    LIME = enum.auto()
    THING = enum.auto()
    WATERMELON = enum.auto()
    PEACH = enum.auto()
    GRAPES = enum.auto()
    LETTUCE = enum.auto()
    EGGPLANT = enum.auto()
    CUCUMB = CUCUMBER = enum.auto()
    COKE = SOFTDRINK = enum.auto()
    PEPSI = SODAPOP = enum.auto()
    MILK = enum.auto()
    PIE = enum.auto()
    CAKE = enum.auto()
    DONUT = enum.auto()
    CUPCAKE = enum.auto()
    CHIPS = enum.auto()
    CANDY = enum.auto()
    CHOCBAR = CHOCOLATEBAR = enum.auto()
    ICECREAM = enum.auto()
    BURGER = enum.auto()
    PIZZA = enum.auto()
    FRIES = enum.auto()
    CHICKENLEG = enum.auto()
    SANDWICH = enum.auto()
    TACO = enum.auto()
    WEENIE = enum.auto()
    HAM = enum.auto()
    CHEESE = enum.auto()
    FLOATLIZARD = enum.auto()
    STANDMONKEY = enum.auto()
    DESTRUCTSCENERY = enum.auto()
    DESTRUCTSCENERYBOMB = TNTDESTRUCTSCENERY = enum.auto()
    COLLAPSESCENERY = enum.auto()
    STOMPSCENERY = enum.auto()
    GEMSTOMP = enum.auto()
    RAVEN = enum.auto()
    TUBETURTLE = enum.auto()
    GEMRING = enum.auto()
    SMALLTREE = enum.auto()
    AMBIENTSOUND = enum.auto()
    UTERUS = enum.auto()
    CRAB = enum.auto()
    WITCH = enum.auto()
    ROCKETTURTLE = enum.auto()
    BUBBA = enum.auto()
    DEVILDEVAN = enum.auto()
    DEVANROBOT = enum.auto()
    ROBOT = enum.auto()
    CARROTUSPOLE = enum.auto()
    PSYCHPOLE = enum.auto()
    DIAMONDUSPOLE = enum.auto()
    FRUITPLATFORM = enum.auto()
    BOLLPLATFORM = enum.auto()
    GRASSPLATFORM = enum.auto()
    PINKPLATFORM = enum.auto()
    SONICPLATFORM = enum.auto()
    SPIKEPLATFORM = enum.auto()
    SPIKEBOLL = enum.auto()
    GENERATOR = enum.auto()
    EVA = enum.auto()
    BUBBLER = enum.auto()
    TNTPOWERUP = enum.auto()
    GUN8POWERUP = enum.auto()
    GUN9POWERUP = enum.auto()
    SPIKEBOLL3D = enum.auto()
    SPRINGCORD = enum.auto()
    BEES = enum.auto()
    COPTER = enum.auto()
    LASERSHIELD = enum.auto()
    STOPWATCH = enum.auto()
    JUNGLEPOLE = enum.auto()
    WARP = enum.auto()
    BIGROCK = enum.auto()
    BIGBOX = enum.auto()
    TRIGGERSCENERY = enum.auto()
    BOLLY = enum.auto()
    BUTTERFLY = enum.auto()
    BEEBOY = enum.auto()
    SNOW = enum.auto()
    TWEEDLEBOSS = enum.auto()
    AIRBOARD = enum.auto()
    CTFBASE = enum.auto()
    XMASNORMTURTLE = enum.auto()
    XMASLIZARD = enum.auto()
    XMASFLOATLIZARD = enum.auto()
    XMASBILSY = enum.auto()
    CAT = enum.auto()
    PACMANGHOST = enum.auto()


class SOUND:
    AMMO_BLUB1 = enum.auto()
    AMMO_BLUB2 = enum.auto()
    AMMO_BMP1 = enum.auto()
    AMMO_BMP2 = enum.auto()
    AMMO_BMP3 = enum.auto()
    AMMO_BMP4 = enum.auto()
    AMMO_BMP5 = enum.auto()
    AMMO_BMP6 = enum.auto()
    AMMO_BOEM1 = enum.auto()
    AMMO_BUL1 = enum.auto()
    AMMO_BULFL1 = enum.auto()
    AMMO_BULFL2 = enum.auto()
    AMMO_BULFL3 = enum.auto()
    AMMO_FIREGUN1A = enum.auto()
    AMMO_FIREGUN2A = enum.auto()
    AMMO_FUMP = enum.auto()
    AMMO_GUN1 = enum.auto()
    AMMO_GUN2 = enum.auto()
    AMMO_GUN3PLOP = enum.auto()
    AMMO_GUNFLP = enum.auto()
    AMMO_GUNFLP1 = enum.auto()
    AMMO_GUNFLP2 = enum.auto()
    AMMO_GUNFLP3 = enum.auto()
    AMMO_GUNFLP4 = enum.auto()
    AMMO_GUNFLPL = enum.auto()
    AMMO_GUNJAZZ = enum.auto()
    AMMO_GUNVELOCITY = enum.auto()
    AMMO_ICEGUN = enum.auto()
    AMMO_ICEGUN2 = enum.auto()
    AMMO_ICEGUNPU = enum.auto()
    AMMO_ICEPU1 = enum.auto()
    AMMO_ICEPU2 = enum.auto()
    AMMO_ICEPU3 = enum.auto()
    AMMO_ICEPU4 = enum.auto()
    AMMO_LASER = enum.auto()
    AMMO_LASER2 = enum.auto()
    AMMO_LASER3 = enum.auto()
    AMMO_LAZRAYS = enum.auto()
    AMMO_MISSILE = enum.auto()
    AMMO_SPZBL1 = enum.auto()
    AMMO_SPZBL2 = enum.auto()
    AMMO_SPZBL3 = enum.auto()
    BAT_BATFLY1 = enum.auto()
    BILSBOSS_BILLAPPEAR = enum.auto()
    BILSBOSS_FINGERSNAP = enum.auto()
    BILSBOSS_FIRE = enum.auto()
    BILSBOSS_FIRESTART = enum.auto()
    BILSBOSS_SCARY3 = enum.auto()
    BILSBOSS_THUNDER = enum.auto()
    BILSBOSS_ZIP = enum.auto()
    BONUS_BONUS1 = enum.auto()
    BONUS_BONUSBLUB = enum.auto()
    BUBBA_BUBBABOUNCE1 = enum.auto()
    BUBBA_BUBBABOUNCE2 = enum.auto()
    BUBBA_BUBBAEXPLO = enum.auto()
    BUBBA_FROG2 = enum.auto()
    BUBBA_FROG3 = enum.auto()
    BUBBA_FROG4 = enum.auto()
    BUBBA_FROG5 = enum.auto()
    BUBBA_SNEEZE2 = enum.auto()
    BUBBA_TORNADOATTACK2 = enum.auto()
    BUMBEE_BEELOOP = enum.auto()
    CATERPIL_RIDOE = enum.auto()
    COMMON_AIRBOARD = enum.auto()
    COMMON_AIRBTURN = enum.auto()
    COMMON_AIRBTURN2 = enum.auto()
    COMMON_BASE1 = enum.auto()
    COMMON_BELL_FIRE = enum.auto()
    COMMON_BELL_FIRE2 = enum.auto()
    COMMON_BENZIN1 = enum.auto()
    COMMON_BIRDFLY = enum.auto()
    COMMON_BIRDFLY2 = enum.auto()
    COMMON_BLOKPLOP = enum.auto()
    COMMON_BLUB1 = enum.auto()
    COMMON_BUBBLGN1 = enum.auto()
    COMMON_BURN = enum.auto()
    COMMON_BURNIN = enum.auto()
    COMMON_CANSPS = enum.auto()
    COMMON_CLOCK = enum.auto()
    COMMON_COIN = enum.auto()
    COMMON_COLLAPS = enum.auto()
    COMMON_CUP = enum.auto()
    COMMON_DAMPED1 = enum.auto()
    COMMON_DOWN = enum.auto()
    COMMON_DOWNFL2 = enum.auto()
    COMMON_DRINKSPAZZ1 = enum.auto()
    COMMON_DRINKSPAZZ2 = enum.auto()
    COMMON_DRINKSPAZZ3 = enum.auto()
    COMMON_DRINKSPAZZ4 = enum.auto()
    COMMON_EAT1 = enum.auto()
    COMMON_EAT2 = enum.auto()
    COMMON_EAT3 = enum.auto()
    COMMON_EAT4 = enum.auto()
    COMMON_ELECTRIC1 = enum.auto()
    COMMON_ELECTRIC2 = enum.auto()
    COMMON_ELECTRICHIT = enum.auto()
    COMMON_EXPL_TNT = enum.auto()
    COMMON_EXPSM1 = enum.auto()
    COMMON_FLAMER = enum.auto()
    COMMON_FLAP = enum.auto()
    COMMON_FOEW1 = enum.auto()
    COMMON_FOEW2 = enum.auto()
    COMMON_FOEW3 = enum.auto()
    COMMON_FOEW4 = enum.auto()
    COMMON_FOEW5 = enum.auto()
    COMMON_GEMSMSH1 = enum.auto()
    COMMON_GLASS2 = enum.auto()
    COMMON_GUNSM1 = enum.auto()
    COMMON_HARP1 = enum.auto()
    COMMON_HEAD = enum.auto()
    COMMON_HELI1 = enum.auto()
    COMMON_HIBELL = enum.auto()
    COMMON_HOLYFLUT = enum.auto()
    COMMON_HORN1 = enum.auto()
    COMMON_ICECRUSH = enum.auto()
    COMMON_IMPACT1 = enum.auto()
    COMMON_IMPACT2 = enum.auto()
    COMMON_IMPACT3 = enum.auto()
    COMMON_IMPACT4 = enum.auto()
    COMMON_IMPACT5 = enum.auto()
    COMMON_IMPACT6 = enum.auto()
    COMMON_IMPACT7 = enum.auto()
    COMMON_IMPACT8 = enum.auto()
    COMMON_IMPACT9 = enum.auto()
    COMMON_ITEMTRE = enum.auto()
    COMMON_JUMP = enum.auto()
    COMMON_JUMP2 = enum.auto()
    COMMON_LAND = enum.auto()
    COMMON_LAND1 = enum.auto()
    COMMON_LAND2 = enum.auto()
    COMMON_LANDCAN1 = enum.auto()
    COMMON_LANDCAN2 = enum.auto()
    COMMON_LANDPOP = enum.auto()
    COMMON_LOADJAZZ = enum.auto()
    COMMON_LOADSPAZ = enum.auto()
    COMMON_METALHIT = enum.auto()
    COMMON_MONITOR = enum.auto()
    COMMON_NOCOIN = enum.auto()
    COMMON_PICKUP1 = enum.auto()
    COMMON_PICKUPW1 = enum.auto()
    COMMON_PISTOL1 = enum.auto()
    COMMON_PLOOP1 = enum.auto()
    COMMON_PLOP1 = enum.auto()
    COMMON_PLOP2 = enum.auto()
    COMMON_PLOP3 = enum.auto()
    COMMON_PLOP4 = enum.auto()
    COMMON_PLOPKORK = enum.auto()
    COMMON_PREEXPL1 = enum.auto()
    COMMON_PREHELI = enum.auto()
    COMMON_REVUP = enum.auto()
    COMMON_RINGGUN = enum.auto()
    COMMON_RINGGUN2 = enum.auto()
    COMMON_SHIELD1 = enum.auto()
    COMMON_SHIELD4 = enum.auto()
    COMMON_SHIELD_ELEC = enum.auto()
    COMMON_SHLDOF3 = enum.auto()
    COMMON_SLIP = enum.auto()
    COMMON_SMASH = enum.auto()
    COMMON_SPLAT1 = enum.auto()
    COMMON_SPLAT2 = enum.auto()
    COMMON_SPLAT3 = enum.auto()
    COMMON_SPLAT4 = enum.auto()
    COMMON_SPLUT = enum.auto()
    COMMON_SPRING1 = enum.auto()
    COMMON_STEAM = enum.auto()
    COMMON_STEP = enum.auto()
    COMMON_STRETCH = enum.auto()
    COMMON_SWISH1 = enum.auto()
    COMMON_SWISH2 = enum.auto()
    COMMON_SWISH3 = enum.auto()
    COMMON_SWISH4 = enum.auto()
    COMMON_SWISH5 = enum.auto()
    COMMON_SWISH6 = enum.auto()
    COMMON_SWISH7 = enum.auto()
    COMMON_SWISH8 = enum.auto()
    COMMON_TELPORT1 = enum.auto()
    COMMON_TELPORT2 = enum.auto()
    COMMON_UP = enum.auto()
    COMMON_WATER = enum.auto()
    COMMON_WOOD1 = enum.auto()
    DEMON_RUN = enum.auto()
    DEVILDEVAN_DRAGONFIRE = enum.auto()
    DEVILDEVAN_FLAP = enum.auto()
    DEVILDEVAN_FROG4 = enum.auto()
    DEVILDEVAN_JUMPUP = enum.auto()
    DEVILDEVAN_LAUGH = enum.auto()
    DEVILDEVAN_PHASER2 = enum.auto()
    DEVILDEVAN_STRECh3 = enum.auto()
    DEVILDEVAN_STRECHTAIL = enum.auto()
    DEVILDEVAN_STRETCH1 = enum.auto()
    DEVILDEVAN_STRETCH3 = enum.auto()
    DEVILDEVAN_VANISH1 = enum.auto()
    DEVILDEVAN_WHISTLEDESCENDING2 = enum.auto()
    DEVILDEVAN_WINGSOUT = enum.auto()
    DOG_AGRESSIV = enum.auto()
    DOG_SNIF1 = enum.auto()
    DOG_WAF1 = enum.auto()
    DOG_WAF2 = enum.auto()
    DOG_WAF3 = enum.auto()
    DRAGFLY_BEELOOP = enum.auto()
    ENDING_OHTHANK = enum.auto()
    ENDTUNEJAZZ_TUNE = enum.auto()
    ENDTUNELORI_CAKE = enum.auto()
    ENDTUNESPAZ_TUNE = enum.auto()
    EPICLOGO_EPIC1 = enum.auto()
    EPICLOGO_EPIC2 = enum.auto()
    EVA_KISS1 = enum.auto()
    EVA_KISS2 = enum.auto()
    EVA_KISS3 = enum.auto()
    EVA_KISS4 = enum.auto()
    FAN_FAN = enum.auto()
    FATCHK_HIT1 = enum.auto()
    FATCHK_HIT2 = enum.auto()
    FATCHK_HIT3 = enum.auto()
    FENCER_FENCE1 = enum.auto()
    FROG_FROG = enum.auto()
    FROG_FROG1 = enum.auto()
    FROG_FROG2 = enum.auto()
    FROG_FROG3 = enum.auto()
    FROG_FROG4 = enum.auto()
    FROG_FROG5 = enum.auto()
    FROG_JAZZ2FROG = enum.auto()
    FROG_TONG = enum.auto()
    GLOVE_HIT = enum.auto()
    HATTER_CUP = enum.auto()
    HATTER_HAT = enum.auto()
    HATTER_PTOEI = enum.auto()
    HATTER_SPLIN = enum.auto()
    HATTER_SPLOUT = enum.auto()
    INTRO_BLOW = enum.auto()
    INTRO_BOEM1 = enum.auto()
    INTRO_BOEM2 = enum.auto()
    INTRO_BRAKE = enum.auto()
    INTRO_END = enum.auto()
    INTRO_GRAB = enum.auto()
    INTRO_GREN1 = enum.auto()
    INTRO_GREN2 = enum.auto()
    INTRO_GREN3 = enum.auto()
    INTRO_GUNM0 = enum.auto()
    INTRO_GUNM1 = enum.auto()
    INTRO_GUNM2 = enum.auto()
    INTRO_HELI = enum.auto()
    INTRO_HITSPAZ = enum.auto()
    INTRO_HITTURT = enum.auto()
    INTRO_IFEEL = enum.auto()
    INTRO_INHALE = enum.auto()
    INTRO_INSECT = enum.auto()
    INTRO_KATROL = enum.auto()
    INTRO_LAND = enum.auto()
    INTRO_MONSTER = enum.auto()
    INTRO_MONSTER2 = enum.auto()
    INTRO_ROCK = enum.auto()
    INTRO_ROPE1 = enum.auto()
    INTRO_ROPE2 = enum.auto()
    INTRO_RUN = enum.auto()
    INTRO_SHOT1 = enum.auto()
    INTRO_SHOTGRN = enum.auto()
    INTRO_SKI = enum.auto()
    INTRO_STRING = enum.auto()
    INTRO_SWISH1 = enum.auto()
    INTRO_SWISH2 = enum.auto()
    INTRO_SWISH3 = enum.auto()
    INTRO_SWISH4 = enum.auto()
    INTRO_UHTURT = enum.auto()
    INTRO_UP1 = enum.auto()
    INTRO_UP2 = enum.auto()
    INTRO_WIND_01 = enum.auto()
    JAZZSOUNDS_BALANCE = enum.auto()
    JAZZSOUNDS_HEY1 = enum.auto()
    JAZZSOUNDS_HEY2 = enum.auto()
    JAZZSOUNDS_HEY3 = enum.auto()
    JAZZSOUNDS_HEY4 = enum.auto()
    JAZZSOUNDS_IDLE = enum.auto()
    JAZZSOUNDS_JAZZV1 = enum.auto()
    JAZZSOUNDS_JAZZV2 = enum.auto()
    JAZZSOUNDS_JAZZV3 = enum.auto()
    JAZZSOUNDS_JAZZV4 = enum.auto()
    JAZZSOUNDS_JUMMY = enum.auto()
    JAZZSOUNDS_PFOE = enum.auto()
    LABRAT_BITE = enum.auto()
    LABRAT_EYE2 = enum.auto()
    LABRAT_EYE3 = enum.auto()
    LABRAT_MOUSE1 = enum.auto()
    LABRAT_MOUSE2 = enum.auto()
    LABRAT_MOUSE3 = enum.auto()
    LIZARD_LIZ1 = enum.auto()
    LIZARD_LIZ2 = enum.auto()
    LIZARD_LIZ4 = enum.auto()
    LIZARD_LIZ6 = enum.auto()
    LORISOUNDS_DIE1 = enum.auto()
    LORISOUNDS_HURT0 = enum.auto()
    LORISOUNDS_HURT1 = enum.auto()
    LORISOUNDS_HURT2 = enum.auto()
    LORISOUNDS_HURT3 = enum.auto()
    LORISOUNDS_HURT4 = enum.auto()
    LORISOUNDS_HURT5 = enum.auto()
    LORISOUNDS_HURT6 = enum.auto()
    LORISOUNDS_HURT7 = enum.auto()
    LORISOUNDS_LORI1 = enum.auto()
    LORISOUNDS_LORI2 = enum.auto()
    LORISOUNDS_LORIBOOM = enum.auto()
    LORISOUNDS_LORIFALL = enum.auto()
    LORISOUNDS_LORIJUMP = enum.auto()
    LORISOUNDS_LORIJUMP2 = enum.auto()
    LORISOUNDS_LORIJUMP3 = enum.auto()
    LORISOUNDS_LORIJUMP4 = enum.auto()
    LORISOUNDS_TOUCH = enum.auto()
    LORISOUNDS_WEHOO = enum.auto()
    MENUSOUNDS_SELECT0 = enum.auto()
    MENUSOUNDS_SELECT1 = enum.auto()
    MENUSOUNDS_SELECT2 = enum.auto()
    MENUSOUNDS_SELECT3 = enum.auto()
    MENUSOUNDS_SELECT4 = enum.auto()
    MENUSOUNDS_SELECT5 = enum.auto()
    MENUSOUNDS_SELECT6 = enum.auto()
    MENUSOUNDS_TYPE = enum.auto()
    MENUSOUNDS_TYPEENTER = enum.auto()
    MONKEY_SPLUT = enum.auto()
    MONKEY_THROW = enum.auto()
    MOTH_FLAPMOTH = enum.auto()
    ORANGE_BOEML = enum.auto()
    ORANGE_BOEMR = enum.auto()
    ORANGE_BUBBELSL = enum.auto()
    ORANGE_BUBBELSR = enum.auto()
    ORANGE_GLAS1L = enum.auto()
    ORANGE_GLAS1R = enum.auto()
    ORANGE_GLAS2L = enum.auto()
    ORANGE_GLAS2R = enum.auto()
    ORANGE_MERGE = enum.auto()
    ORANGE_SWEEP0L = enum.auto()
    ORANGE_SWEEP0R = enum.auto()
    ORANGE_SWEEP1L = enum.auto()
    ORANGE_SWEEP1R = enum.auto()
    ORANGE_SWEEP2L = enum.auto()
    ORANGE_SWEEP2R = enum.auto()
    P2_CRUNCH = enum.auto()
    P2_FART = enum.auto()
    P2_FOEW1 = enum.auto()
    P2_FOEW4 = enum.auto()
    P2_FOEW5 = enum.auto()
    P2_FROG1 = enum.auto()
    P2_FROG2 = enum.auto()
    P2_FROG3 = enum.auto()
    P2_FROG4 = enum.auto()
    P2_FROG5 = enum.auto()
    P2_KISS4 = enum.auto()
    P2_OPEN = enum.auto()
    P2_PINCH1 = enum.auto()
    P2_PINCH2 = enum.auto()
    P2_PLOPSEQ1 = enum.auto()
    P2_PLOPSEQ2 = enum.auto()
    P2_PLOPSEQ3 = enum.auto()
    P2_PLOPSEQ4 = enum.auto()
    P2_POEP = enum.auto()
    P2_PTOEI = enum.auto()
    P2_SPLOUT = enum.auto()
    P2_SPLUT = enum.auto()
    P2_THROW = enum.auto()
    P2_TONG = enum.auto()
    PICKUPS_BOING_CHECK = enum.auto()
    PICKUPS_HELI2 = enum.auto()
    PICKUPS_STRETCH1A = enum.auto()
    PINBALL_BELL = enum.auto()
    PINBALL_FLIP1 = enum.auto()
    PINBALL_FLIP2 = enum.auto()
    PINBALL_FLIP3 = enum.auto()
    PINBALL_FLIP4 = enum.auto()
    QUEEN_LADYUP = enum.auto()
    QUEEN_SCREAM = enum.auto()
    RAPIER_GOSTDIE = enum.auto()
    RAPIER_GOSTLOOP = enum.auto()
    RAPIER_GOSTOOOH = enum.auto()
    RAPIER_GOSTRIP = enum.auto()
    RAPIER_HITCHAR = enum.auto()
    ROBOT_BIG1 = enum.auto()
    ROBOT_BIG2 = enum.auto()
    ROBOT_CAN1 = enum.auto()
    ROBOT_CAN2 = enum.auto()
    ROBOT_HYDRO = enum.auto()
    ROBOT_HYDRO2 = enum.auto()
    ROBOT_HYDROFIL = enum.auto()
    ROBOT_HYDROPUF = enum.auto()
    ROBOT_IDLE1 = enum.auto()
    ROBOT_IDLE2 = enum.auto()
    ROBOT_JMPCAN1 = enum.auto()
    ROBOT_JMPCAN10 = enum.auto()
    ROBOT_JMPCAN2 = enum.auto()
    ROBOT_JMPCAN3 = enum.auto()
    ROBOT_JMPCAN4 = enum.auto()
    ROBOT_JMPCAN5 = enum.auto()
    ROBOT_JMPCAN6 = enum.auto()
    ROBOT_JMPCAN7 = enum.auto()
    ROBOT_JMPCAN8 = enum.auto()
    ROBOT_JMPCAN9 = enum.auto()
    ROBOT_METAL1 = enum.auto()
    ROBOT_METAL2 = enum.auto()
    ROBOT_METAL3 = enum.auto()
    ROBOT_METAL4 = enum.auto()
    ROBOT_METAL5 = enum.auto()
    ROBOT_OPEN = enum.auto()
    ROBOT_OUT = enum.auto()
    ROBOT_POEP = enum.auto()
    ROBOT_POLE = enum.auto()
    ROBOT_SHOOT = enum.auto()
    ROBOT_STEP1 = enum.auto()
    ROBOT_STEP2 = enum.auto()
    ROBOT_STEP3 = enum.auto()
    ROCK_ROCK1 = enum.auto()
    RUSH_RUSH = enum.auto()
    SCIENCE_PLOPKAOS = enum.auto()
    SKELETON_BONE1 = enum.auto()
    SKELETON_BONE2 = enum.auto()
    SKELETON_BONE3 = enum.auto()
    SKELETON_BONE5 = enum.auto()
    SKELETON_BONE6 = enum.auto()
    SKELETON_BONE7 = enum.auto()
    SMALTREE_FALL = enum.auto()
    SMALTREE_GROUND = enum.auto()
    SMALTREE_HEAD = enum.auto()
    SONCSHIP_METAL1 = enum.auto()
    SONCSHIP_MISSILE2 = enum.auto()
    SONCSHIP_SCRAPE = enum.auto()
    SONCSHIP_SHIPLOOP = enum.auto()
    SONCSHIP_TARGETLOCK = enum.auto()
    SPAZSOUNDS_AUTSCH1 = enum.auto()
    SPAZSOUNDS_AUTSCH2 = enum.auto()
    SPAZSOUNDS_BIRDSIT = enum.auto()
    SPAZSOUNDS_BURP = enum.auto()
    SPAZSOUNDS_CHIRP = enum.auto()
    SPAZSOUNDS_EATBIRD = enum.auto()
    SPAZSOUNDS_HAHAHA = enum.auto()
    SPAZSOUNDS_HAHAHA2 = enum.auto()
    SPAZSOUNDS_HAPPY = enum.auto()
    SPAZSOUNDS_HIHI = enum.auto()
    SPAZSOUNDS_HOHOHO1 = enum.auto()
    SPAZSOUNDS_HOOO = enum.auto()
    SPAZSOUNDS_KARATE7 = enum.auto()
    SPAZSOUNDS_KARATE8 = enum.auto()
    SPAZSOUNDS_OHOH = enum.auto()
    SPAZSOUNDS_OOOH = enum.auto()
    SPAZSOUNDS_WOOHOO = enum.auto()
    SPAZSOUNDS_YAHOO = enum.auto()
    SPAZSOUNDS_YAHOO2 = enum.auto()
    SPRING_BOING_DOWN = enum.auto()
    SPRING_SPRING1 = enum.auto()
    STEAM_STEAM = enum.auto()
    STONED_STONED = enum.auto()
    SUCKER_FART = enum.auto()
    SUCKER_PINCH1 = enum.auto()
    SUCKER_PINCH2 = enum.auto()
    SUCKER_PINCH3 = enum.auto()
    SUCKER_PLOPSEQ1 = enum.auto()
    SUCKER_PLOPSEQ2 = enum.auto()
    SUCKER_PLOPSEQ3 = enum.auto()
    SUCKER_PLOPSEQ4 = enum.auto()
    SUCKER_UP = enum.auto()
    TUFBOSS_CATCH = enum.auto()
    TUFBOSS_RELEASE = enum.auto()
    TUFBOSS_SWING = enum.auto()
    TURTLE_BITE3 = enum.auto()
    TURTLE_HIDE = enum.auto()
    TURTLE_HITSHELL = enum.auto()
    TURTLE_IDLE1 = enum.auto()
    TURTLE_IDLE2 = enum.auto()
    TURTLE_NECK = enum.auto()
    TURTLE_SPK1TURT = enum.auto()
    TURTLE_SPK2TURT = enum.auto()
    TURTLE_SPK3TURT = enum.auto()
    TURTLE_SPK4TURT = enum.auto()
    TURTLE_TURN = enum.auto()
    UTERUS_CRABCLOSE = enum.auto()
    UTERUS_CRABOPEN2 = enum.auto()
    UTERUS_SCISSORS1 = enum.auto()
    UTERUS_SCISSORS2 = enum.auto()
    UTERUS_SCISSORS3 = enum.auto()
    UTERUS_SCISSORS4 = enum.auto()
    UTERUS_SCISSORS5 = enum.auto()
    UTERUS_SCISSORS6 = enum.auto()
    UTERUS_SCISSORS7 = enum.auto()
    UTERUS_SCISSORS8 = enum.auto()
    UTERUS_SCREAM1 = enum.auto()
    UTERUS_STEP1 = enum.auto()
    UTERUS_STEP2 = enum.auto()
    WIND_WIND2A = enum.auto()
    WITCH_LAUGH = enum.auto()
    WITCH_MAGIC = enum.auto()
    XBILSY_BILLAPPEAR = enum.auto()
    XBILSY_FINGERSNAP = enum.auto()
    XBILSY_FIRE = enum.auto()
    XBILSY_FIRESTART = enum.auto()
    XBILSY_SCARY3 = enum.auto()
    XBILSY_THUNDER = enum.auto()
    XBILSY_ZIP = enum.auto()
    XLIZARD_LIZ1 = enum.auto()
    XLIZARD_LIZ2 = enum.auto()
    XLIZARD_LIZ4 = enum.auto()
    XLIZARD_LIZ6 = enum.auto()
    XTURTLE_BITE3 = enum.auto()
    XTURTLE_HIDE = enum.auto()
    XTURTLE_HITSHELL = enum.auto()
    XTURTLE_IDLE1 = enum.auto()
    XTURTLE_IDLE2 = enum.auto()
    XTURTLE_NECK = enum.auto()
    XTURTLE_SPK1TURT = enum.auto()
    XTURTLE_SPK2TURT = enum.auto()
    XTURTLE_SPK3TURT = enum.auto()
    XTURTLE_SPK4TURT = enum.auto()
    XTURTLE_TURN = enum.auto()
    ZDOG_AGRESSIV = enum.auto()
    ZDOG_SNIF1 = enum.auto()
    ZDOG_WAF1 = enum.auto()
    ZDOG_WAF2 = enum.auto()
    ZDOG_WAF3 = enum.auto()


class TEXTURE(enum.Enum):
    NORMAL = "normal.png"
    BLADE = "blade.png"
    CORRUPTEDSANCTUARY = "corruptedsanctuary.png"
    DESOLATION = "desolation.png"
    DIAMONDUSBETA = "diamondusbeta.png"
    ICTUBELECTRIC = "ictubelectric.png"
    MEDIVO = "medivo.png"
    MEZ02 = "mez02.png"
    MUCKAMOKNIGHT = "muckamoknight.png"
    PSYCH = "psych.png"
    RANEFORUSV = "raneforusv.png"
    WINDSTORMFORTRESS = "windstormfortress.png"
    WISETYNESS = "wisetyness.png"
    WTF = "wtf.png"
    XARGON = "xargon.png"


TEXTURE_URL = "https://www.jazz2online.com/jj2plus/textures/"


class SPRITEMODE(enum.IntEnum):
    ALPHAMAP = enum.auto()
    BLEND_NORMAL = enum.auto()
    BLEND_DISSOLVE = enum.auto()
    BLEND_DARKEN = enum.auto()
    BLEND_MULTIPLY = enum.auto()
    BLEND_BURN = enum.auto()
    BLEND_LIGHTEN = enum.auto()
    BLEND_SCREEN = enum.auto()
    BLEND_DODGE = enum.auto()
    BLEND_OVERLAY = enum.auto()
    BLEND_SOFTLIGHT = enum.auto()
    BLEND_HARDLIGHT = enum.auto()
    BLEND_DIFFERENCE = enum.auto()
    BLEND_EXCLUSION = enum.auto()
    BLEND_COLOR = enum.auto()
    BLEND_HUE = enum.auto()
    BLEND_SATURATION = enum.auto()
    BLEND_LUMINANCE = enum.auto()
    BRIGHTNESS = enum.auto()
    FROZEN = enum.auto()
    GEM = enum.auto()
    INVISIBLE = enum.auto()
    MENUPLAYER = enum.auto()
    NEONGLOW = enum.auto()
    NORMAL = enum.auto()
    PALSHIFT = enum.auto()
    PLAYER = enum.auto()
    RESIZED = enum.auto()
    SHADOW = enum.auto()
    SINGLECOLOR = enum.auto()
    SINGLEHUE = enum.auto()
    TINTED = enum.auto()
    TRANSLUCENT = enum.auto()
    TRANSLUCENTCOLOR = enum.auto()
    TRANSLUCENTPALSHIFT = enum.auto()
    TRANSLUCENTPLAYER = enum.auto()
    TRANSLUCENTSINGLEHUE = enum.auto()
    TRANSLUCENTTILE = enum.auto()


class ANIMRABBIT(enum.IntEnum):
    AIRBOARD = enum.auto()
    AIRBOARDTURN = enum.auto()
    BUTTSTOMPLAND = enum.auto()
    CORPSE = enum.auto()
    DIE = enum.auto()
    DIVE = enum.auto()
    DIVEFIREQUIT = enum.auto()
    DIVEFIRERIGHT = enum.auto()
    DIVEUP = enum.auto()
    EARBRACHIATE = enum.auto()
    ENDOFLEVEL = enum.auto()
    FALL = enum.auto()
    FALLBUTTSTOMP = enum.auto()
    FALLLAND = enum.auto()
    FIRE = enum.auto()
    FIREUP = enum.auto()
    FIREUPQUIT = enum.auto()
    FROG = enum.auto()
    HANGFIREQUIT = enum.auto()
    HANGFIREREST = enum.auto()
    HANGFIREUP = enum.auto()
    HANGIDLE1 = enum.auto()
    HANGIDLE2 = enum.auto()
    HANGINGFIREQUIT = enum.auto()
    HANGINGFIRERIGHT = enum.auto()
    HELICOPTER = enum.auto()
    HELICOPTERFIREQUIT = enum.auto()
    HELICOPTERFIRERIGHT = enum.auto()
    HPOLE = enum.auto()
    HURT = enum.auto()
    IDLE1 = enum.auto()
    IDLE2 = enum.auto()
    IDLE3 = enum.auto()
    IDLE4 = enum.auto()
    IDLE5 = enum.auto()
    JUMPFIREQUIT = enum.auto()
    JUMPFIRERIGHT = enum.auto()
    JUMPING1 = enum.auto()
    JUMPING2 = enum.auto()
    JUMPING3 = enum.auto()
    LEDGEWIGGLE = enum.auto()
    LIFT = enum.auto()
    LIFTJUMP = enum.auto()
    LIFTLAND = enum.auto()
    LOOKUP = enum.auto()
    LOOPY = enum.auto()
    PUSH = enum.auto()
    QUIT = enum.auto()
    REV1 = enum.auto()
    REV2 = enum.auto()
    REV3 = enum.auto()
    RIGHTFALL = enum.auto()
    RIGHTJUMP = enum.auto()
    ROLLING = enum.auto()
    RUN1 = enum.auto()
    RUN2 = enum.auto()
    RUN3 = enum.auto()
    SKID1 = enum.auto()
    SKID2 = enum.auto()
    SKID3 = enum.auto()
    SPRING = enum.auto()
    STAND = enum.auto()
    STATIONARYJUMP = enum.auto()
    STATIONARYJUMPEND = enum.auto()
    STATIONARYJUMPSTART = enum.auto()
    STONED = enum.auto()
    SWIMDOWN = enum.auto()
    SWIMRIGHT = enum.auto()
    SWIMTURN1 = enum.auto()
    SWIMTURN2 = enum.auto()
    SWIMUP = enum.auto()
    SWINGINGVINE = enum.auto()
    TELEPORT = enum.auto()
    TELEPORTFALL = enum.auto()
    TELEPORTFALLING = enum.auto()
    TELEPORTFALLTELEPORT = enum.auto()
    TELEPORTSTAND = enum.auto()
    VPOLE = enum.auto()


class ANIM(enum.IntEnum):
    AMMO = enum.auto()
    BAT = enum.auto()
    BEEBOY = enum.auto()
    BEES = enum.auto()
    BIGBOX = enum.auto()
    BIGROCK = enum.auto()
    BIGTREE = enum.auto()
    BILSBOSS = enum.auto()
    BIRD = enum.auto()
    BIRD3D = enum.auto()
    BOLLPLAT = enum.auto()
    BONUS = enum.auto()
    BOSS = enum.auto()
    BRIDGE = enum.auto()
    BUBBA = enum.auto()
    BUMBEE = enum.auto()
    BUTTERFLY = enum.auto()
    CARROTPOLE = enum.auto()
    CAT = enum.auto()
    CAT2 = enum.auto()
    CATERPIL = enum.auto()
    CHUCK = enum.auto()
    COMMON = enum.auto()
    CONTINUE = enum.auto()
    DEMON = enum.auto()
    DESTSCEN = enum.auto()
    DEVAN = enum.auto()
    DEVILDEVAN = enum.auto()
    DIAMPOLE = enum.auto()
    DOG = enum.auto()
    DOOR = enum.auto()
    DRAGFLY = enum.auto()
    DRAGON = enum.auto()
    EVA = enum.auto()
    FACES = enum.auto()
    FATCHK = enum.auto()
    FENCER = enum.auto()
    FISH = enum.auto()
    FLAG = enum.auto()
    FLARE = enum.auto()
    FONT = enum.auto()
    FROG = enum.auto()
    FRUITPLAT = enum.auto()
    GEMRING = enum.auto()
    GLOVE = enum.auto()
    GRASSPLAT = enum.auto()
    HATTER = enum.auto()
    HELMUT = enum.auto()
    JAZZ = enum.auto()
    JAZZ3D = enum.auto()
    JUNGLEPOLE = enum.auto()
    LABRAT = enum.auto()
    LIZARD = enum.auto()
    LORI = enum.auto()
    LORI2 = enum.auto()
    MENU = enum.auto()
    MENUFONT = enum.auto()
    MONKEY = enum.auto()
    MOTH = enum.auto()
    PICKUPS = enum.auto()
    PINBALL = enum.auto()
    PINKPLAT = enum.auto()
    PSYCHPOLE = enum.auto()
    QUEEN = enum.auto()
    RAPIER = enum.auto()
    RAVEN = enum.auto()
    ROBOT = enum.auto()
    ROCK = enum.auto()
    ROCKTURT = enum.auto()
    SKELETON = enum.auto()
    SMALTREE = enum.auto()
    SNOW = enum.auto()
    SONCSHIP = enum.auto()
    SONICPLAT = enum.auto()
    SPARK = enum.auto()
    SPAZ = enum.auto()
    SPAZ2 = enum.auto()
    SPAZ3D = enum.auto()
    SPIKEBOLL = enum.auto()
    SPIKEBOLL3D = enum.auto()
    SPIKEPLAT = enum.auto()
    SPRING = enum.auto()
    STEAM = enum.auto()
    SUCKER = enum.auto()
    TUBETURT = enum.auto()
    TUFBOSS = enum.auto()
    TUFTUR = enum.auto()
    TURTLE = enum.auto()
    TWEEDLE = enum.auto()
    UTERUS = enum.auto()
    VINE = enum.auto()
    WARP10 = enum.auto()
    WARP100 = enum.auto()
    WARP20 = enum.auto()
    WARP50 = enum.auto()
    WITCH = enum.auto()
    XBILSY = enum.auto()
    XLIZARD = enum.auto()
    XTURTLE = enum.auto()
    ZDOG = enum.auto()
    ZSPARK = enum.auto()


ANIM.RABBIT = ANIMRABBIT


DISCONNECT_MESSAGES = {
    'Unknown error': 1,
    'Version different': 2,
    'Server is full': 3,
    'Error during handshaking': 4,
    'Feature not supported in shareware': 5,
    'Error downloading level': 6,
    'Connection lost': 7,
    'Winsock error': 8,
    'Connection timed out': 9,
    'Server stopped': 10,
    'Kicked off': 11,
    'Banned': 12,
    'Denied': 13,  # Starting from 13 are JJ2+
    'Version of JJ2+ is different': 14,
    'Server kicked you for idling': 15,
    'No downloads allowed': 16,
    'Unauthorized file request': 17,
    'No splitscreeners allowed': 18,
    'Kicked for spamming': 19
}


class GAMEEVENT(enum.IntEnum):
    PLAYER_ROASTED = 10
    BULLET_SHOT = 16


VERSIONSTRING = {
    (1, 23): '21  ',
    (1, 24): '24  ',
}


PLUSTIMESTAMP = {
    (5, 9): bytes((0x20, 0x03, 0x09, 0x00, 0x05, 0x00)),  # 2021-05-11
    (5, 7): bytes((0x20, 0x03, 0x00, 0x00, 0x06, 0x00)),  # 2021-05-11
    (4, 1): bytes((0x20, 0x01, 0x01, 0x00, 0x04, 0x00)),  # 2021-05-11
}


BIN_DISCONNECTMESSAGE = Mapping(Byte, DISCONNECT_MESSAGES)
BIN_VERSIONSTRING = Mapping(PaddedString(4, 'ascii'), VERSIONSTRING)
BIN_CHAR = Enum(Byte, CHARACTER)
BIN_TEAM = Enum(Byte, TEAM)
BIN_GAMEMODE = Enum(Byte, GAME.MODE)
BIN_CUSTOM = Enum(Byte, GAME.CUSTOM)
BIN_GAMEEVENT = Enum(Byte, GAMEEVENT)
BIN_CHAT = Enum(Byte, CHAT)
BIN_SPECTATETARGET = Enum(Int8sb, SPECTATETARGET)
BIN_PLUSTIMESTAMP = Mapping(Bytes(6), PLUSTIMESTAMP)

LATEST_PLUS_VERSION = (5, 9)
